version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mas-my-appointment-schedule
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules